lista = [1,2,3,4,5,6,7,8,9,10]
print(lista)
lista.append(11)
print(lista)
lista.pop(2)
print(lista)
lista.reverse()
print(lista)
lista.sort()
print("Ordem crescente:", lista)
lista.sort(reverse=True)
print("Ordem decrescente:", lista)
print(max(lista))
print(min(lista))